name: The Aranasaurus Nest
url: http://aranasaurus.com
description: Where @aranasaurus keeps his code and things
twitter: aranasaurus
github: aranasaurus

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: 'pygments'

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
